name: sub_notes_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  flutter_svg: ^2.0.11
  flutter_dotenv: ^5.2.1
  package_info_plus: ^8.1.0
  internet_connection_checker_plus: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/animations/
    - assets/lottie-animations/
